### ISSUE TITLE
You can take some questions

### ISSUE THREAD

**Issue by meetgyn** [MS-WEB-BN/t14m4t#2]
I tested the tool, it worked without errors. But I didn't understand the result.
For example she returned me:
[80][http-get] host: 172.20.3.8   login: admin   password: anonymous
And
443][http-get] host: 172.20.3.8   login: admin   password: password
But I didn't understand where to use these passwords.

**Comment by MS-WEB-BN** [comment]
@meetgyn This is not related to functionality of t14m4t, therefore I will close it. 
Those are credentials for HTTP authentication. In some cases where it is not present, hydra outputs it as if the password had been found.
